// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestApiTesting.Framework.Cheetah.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetPostsFeature : Xunit.IClassFixture<GetPostsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetPosts.feature"
#line hidden
        
        public GetPostsFeature(GetPostsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetPosts", "As a non-authenticated user,\r\nI want the ability to get a post.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
  #line 6
    testRunner.Given("I have a client \"client1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="A non-authenticated user successfully gets a post")]
        [Xunit.TraitAttribute("FeatureTitle", "GetPosts")]
        [Xunit.TraitAttribute("Description", "A non-authenticated user successfully gets a post")]
        [Xunit.TraitAttribute("Category", "AcceptanceCriteria")]
        public virtual void ANon_AuthenticatedUserSuccessfullyGetsAPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A non-authenticated user successfully gets a post", null, new string[] {
                        "AcceptanceCriteria"});
#line 9
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 10
    testRunner.Given("I have a string \"sunt aut facere repellat provident occaecati excepturi optio rep" +
                    "rehenderit\" named \"title1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
      testRunner.And("I have a string \"quia et suscipit suscipit recusandae consequuntur expedita et cu" +
                    "m reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem even" +
                    "iet architecto\" named \"body1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
      testRunner.And("I have an int \"1\" named \"one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
     testRunner.When("I send a \"Get\" request to \"/posts/1\" using client \"client1\" and get the response " +
                    "\"deletePostsResponse1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
      testRunner.And("I get the content \"deletePostsResponse1Body\" of the response \"deletePostsResponse" +
                    "1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
     testRunner.Then("the response \"deletePostsResponse1\" should have the status code \"OK\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
      testRunner.And("the \"userId\" of \"deletePostsResponse1Body\" should be \"one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
      testRunner.And("the \"id\" of \"deletePostsResponse1Body\" should be \"one\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
      testRunner.And("the \"title\" of \"deletePostsResponse1Body\" should be \"title1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
      testRunner.And("I compare \"body\" of \"deletePostsResponse1Body\" with \"body1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
      testRunner.And("the modified \"body\" of \"deletePostsResponse1Body\" should be modified \"body1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="A non-authenticated user attempts to get a post with nonexistent id")]
        [Xunit.TraitAttribute("FeatureTitle", "GetPosts")]
        [Xunit.TraitAttribute("Description", "A non-authenticated user attempts to get a post with nonexistent id")]
        [Xunit.TraitAttribute("Category", "NegativePath")]
        public virtual void ANon_AuthenticatedUserAttemptsToGetAPostWithNonexistentId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A non-authenticated user attempts to get a post with nonexistent id", null, new string[] {
                        "NegativePath"});
#line 23
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
  this.FeatureBackground();
#line 24
     testRunner.When("I send a \"Get\" request to \"/posts/101\" using client \"client1\" and get the respons" +
                    "e \"deletePostsResponse1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
      testRunner.And("I get the content \"deletePostsResponse1Body\" of the response \"deletePostsResponse" +
                    "1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
     testRunner.Then("the response \"deletePostsResponse1\" should have the status code \"Not Found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetPostsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetPostsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
